#!/bin/bash

CHEF="${HOME}/.chef"

user=${1}
type=${2}
if test -z "${user}" ; then
  exit 1
fi

key="${user}.pem"
if test -r "${key}" ; then
  echo "Remove key: ${key}"
  exit 1
fi

echo "Create client ${user}?"
read -p "Enter to continue, Ctrl+C to abort"

knife client create ${user} -d ${type} -f ${key}

echo "Copy to vagrant?"
read
cp ${HOME}/.chef/validation.pem /vagrant/chef-validator.pem
cp ${HOME}/${key} /vagrant/

