#!/bin/bash

chef="server-webui server solr expander"

echo "Fix chef links?"
read -p "Enter to continue, Ctrl+C to abort"

cd /usr/bin
for i in ${chef} ; do
  j="chef-${i}"
  if test -L "${j}" ; then continue ; fi
  sudo ln -s "/usr/sbin/${j}" "${j}"
done

for i in ${chef} ; do
  j="chef-${i}"
  sudo /etc/init.d/${j} restart
done
